=== WebOfTrust/schema/oobi/EN6Oh5XSD5_q2Hgu-aqpdfbVepdpYpFlgz6zvJL5b_r5/index.json
{
    "$id": "EN6Oh5XSD5_q2Hgu-aqpdfbVepdpYpFlgz6zvJL5b_r5",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Designated Aliases Public Attestation",
    "description": "A public attestation listing the designated aliases of an AID controller.",
    "type": "object",
    "credentialType": "DesignatedAliasesPublicAttestation",
    "version": "1.0.0",
    "properties": {
        "v": {
            "description": "Version",
            "type": "string"
        },
        "d": {
            "description": "Attestation SAID",
            "type": "string"
        },
        "i": {
            "description": "Controller AID",
            "type": "string"
        },
        "ri": {
            "description": "Attestation status registry",
            "type": "string"
        },
        "s": {
            "description": "schema section",
            "oneOf": [
                {
                    "description": "schema section SAID",
                    "type": "string"
                },
                {
                    "description": "schema detail",
                    "type": "object"
                }
            ]
        },
        "a": {
            "oneOf": [
                {
                    "description": "Attributes block SAID",
                    "type": "string"
                },
                {
                    "$id": "EBMVc1eOhOaA7MdwAlAX3KcvJRTpFrc7_xcB_XveYAEE",
                    "description": "Attributes block",
                    "type": "object",
                    "properties": {
                        "d": {
                            "description": "Attributes block SAID",
                            "type": "string"
                        },
                        "dt": {
                            "description": "Designation date time",
                            "type": "string",
                            "format": "date-time"
                        },
                        "ids": {
                            "description": "List of namespaced/controlled AID aliases designated by the AID controller",
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "additionalProperties": false,
                    "required": [
                        "d",
                        "dt",
                        "ids"
                    ]
                }
            ]
        },
        "r": {
            "oneOf": [
                {
                    "description": "Rules block SAID",
                    "type": "string"
                },
                {
                    "$id": "EHbxC6vD0mU49geUxIfcQtTxP2tAqay7QCz3CVzfSdHz",
                    "description": "Rules block",
                    "type": "object",
                    "properties": {
                        "d": {
                            "description": "Rules block SAID",
                            "type": "string"
                        },
                        "aliasDesignation": {
                            "description": "Alias designation",
                            "type": "object",
                            "properties": {
                                "l": {
                                    "type": "string",
                                    "const": "The issuer of this ACDC designates the identifiers in the ids field as the only allowed namespaced aliases of the issuer's AID."
                                }
                            }
                        },
                        "usageDisclaimer": {
                            "description": "Usage Disclaimer",
                            "type": "object",
                            "properties": {
                                "l": {
                                    "description": "Limitation of designation scope",
                                    "type": "string",
                                    "const": "This attestation only asserts designated aliases of the controller of the AID, that the AID controlled namespaced alias has been designated by the controller. It does not assert that the controller of this AID has control over the infrastructure or anything else related to the namespace other than the included AID."
                                }
                            }
                        },
                        "issuanceDisclaimer": {
                            "description": "Issuance Disclaimer",
                            "type": "object",
                            "properties": {
                                "l": {
                                    "description": "Accuracy of information",
                                    "type": "string",
                                    "const": "All information in a valid and non-revoked alias designation assertion is accurate as of the date specified."
                                }
                            }
                        },
                        "termsOfUse": {
                            "description": "Terms of use",
                            "type": "object",
                            "properties": {
                                "l": {
                                    "type": "string",
                                    "const": "Designated aliases of the AID must only be used in a manner consistent with the expressed intent of the AID controller."
                                }
                            }
                        }
                    },
                    "additionalProperties": false,
                    "required": [
                        "d",
                        "aliasDesignation",
                        "usageDisclaimer",
                        "issuanceDisclaimer",
                        "termsOfUse"
                    ]
                }
            ]
        }
    },
    "additionalProperties": false,
    "required": [
        "v",
        "d",
        "i",
        "ri",
        "s",
        "a",
        "r"
    ]
}

=== WebOfTrust/schema/desig-aliases/examples/desig-aliases-public.json
{
    "v": "ACDC10JSON000514_",
    "d": "EMVnFMfhcw67coSNnH5nqi5fWtFreCNuw6pGVGdMFuSx",
    "i": "ENro7uf0ePmiK3jdTo2YCdXLqW7z7xoP6qhhBou6gBLe",
    "ri": "EFfjfmq3DiHAbVWiF4VA24fP5OEIV1EhWoO-v3ZqmVG6",
    "s": "EN6Oh5XSD5_q2Hgu-aqpdfbVepdpYpFlgz6zvJL5b_r5",
    "a": {
        "d": "EHQgqNNSueVmVjlErrGtzjl-HJya9rMUiNadDSkZQ1kV",
        "dt": "2023-11-13T17:41:37.710691+00:00",
        "ids": [
            "did:webs:foo.com:ENro7uf0ePmiK3jdTo2YCdXLqW7z7xoP6qhhBou6gBLe",
            "did:web:example.com:ENro7uf0ePmiK3jdTo2YCdXLqW7z7xoP6qhhBou6gBLe"
        ]
    },
    "r": {
        "d": "EEVTx0jLLZDQq8a5bXrXgVP0JDP7j8iDym9Avfo8luLw",
        "aliasDesignation": {
            "l": "The issuer of this ACDC designates the identifiers in the ids field as the only allowed namespaced aliases of the issuer's AID."
        },
        "usageDisclaimer": {
            "l": "This attestation only asserts designated aliases of the controller of the AID, that the AID controlled namespaced alias has been designated by the controller. It does not assert that the controller of this AID has control over the infrastructure or anything else related to the namespace other than the included AID."
        },
        "issuanceDisclaimer": {
            "l": "All information in a valid and non-revoked alias designation assertion is accurate as of the date specified."
        },
        "termsOfUse": {
            "l": "Designated aliases of the AID must only be used in a manner consistent with the expressed intent of the AID controller."
        }
    }
}
