=== WebOfTrust/schema/face-to-face/schema.json
{
  "$id": "EMwdW1RO1TvOmTMrli_fej8GYn-3tSl27xMyDDf0jigK",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "face-to-face",
  "description": "Assert that an issuer knows the issuee to be a human being, based one or more face-to-face interactions.",
  "$comment": "These credentials have no edges. They can be chained by showing that the issuer's identifier is also an identifier associated with another credential of whatever type, but they do not require chaining.",
  "type": "object",
  "credentialType": "faceToFaceCredential",
  "version": "1.0.0",
  "required": [
    "d",
    "i",
    "ri",
    "s",
    "a",
    "r"
  ],
  "properties": {
    "v": {
      "description": "Version string using ACDC conventions",
      "type": "string"
    },
    "d": {
      "description": "SAID of the credential",
      "type": "string"
    },
    "i": {
      "description": "Identifier of the issuer",
      "type": "string"
    },
    "ri": {
      "description": "Registry for issuer's credential status",
      "type": "string"
    },
    "s": {
      "description": "SAID of this schema",
      "type": "string"
    },
    "a": {
      "oneOf": [
        {
          "description": "SAID of attributes block",
          "type": "string"
        },
        {
          "$id": "EDv4wiOMHE125CXu-EuOd0YRXz-AgpLilJfjoODFqtHD",
          "description": "Attributes block",
          "type": "object",
          "required": ["d", "u", "i", "dt", "minutes"],
          "properties": {
            "d": {
              "description": "SAID of attributes block",
              "type": "string"
            },
            "u": {
              "description": "A salty nonce",
              "type": "string"
            },
            "i": {
              "description": "Identifier that issuee controls, according to issuer",
              "type": "string"
            },
            "knownAs": {
              "description": "Name by which issuer knows issuee (may be a nickname, a first or last name only, or a full name)",
              "type": "string"
            },
            "minutes": {
              "description": "At least how many minutes has issuer spent with issuee, face-to-face in real life?",
              "type": "integer",
              "exclusiveMin": 0
            },
            "dt": {
              "description": "Time as of which the issuer asserts the face-to-face interaction (and any other information about the issuee) to be fresh. This may be before the time of issuance.",
              "format": "date-time",
              "type": "string"
            },
            "biometricHashes": {
              "description": "Hashes of photos, voiceprints, or biometric enrollments that the issuer attests represents the issuee accurately, in real life",
              "type": "array",
              "uniqueItems": true,
              "minItems": 1,
              "items": {
                "format": "cesr",
                "type": "string"
              }
            },
            "confirmedHandles": {
              "description": "Handles that the issuer has personally used to interact with the issuee",
              "type": "array",
              "uniqueItems": true,
              "minItems": 1,
              "items": {
                "$comment": "First part of string identifies a scope; second part is handle in that scope",
                "examples": ["github:abc123.xyz", "twitter:tweetsasx", "mailto:fred@acme.com", "linkedin:foobargeek", "btc:bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq"],
                "type": "string",
                "pattern": "^([a-z0-9-_.]+):([A-Za-z0-9@-_.]+)$"
              }
            },
            "basis": {
              "description": "Strongest reason that issuer wants to cite as proof that they have accurate knowledge of the issuee as a human being",
              "type": "string",
              "$comment": "Enum omitted to allow flexibility. However, use example values if they apply. NIST IAL values are mostly about identification, not personhood, but may provide clarity about interaction type.",
              "examples": ["family", "friend", "colleague", "acquaintance", "nist-ial1", "nist-ial2", "nist-ial3"],
              "pattern": "^[-a-z0-0 ]+$"
            },
            "caveats": {
              "description": "Note about limits on issuer observations of issuee during face-to-face",
              "type": "string"
            }
          }
        }
      ]
    },
    "r": {
      "description": "SAID of rules block",
      "type": "string",
      "const": "EE1ycWdqBAE_4F-WsXZM83CrjpyCClYgPeINk104bLKX",
      "format": "cesr"
    }
  },
  "additionalProperties": false
}

=== WebOfTrust/schema/face-to-face/example.json
{
  "v": "ACDC10JSON00011c_",
  "d": "EMqNHUFjZNmyYzT32xGbzFoBMfCNOtACXCi1xgtpMLEp",
  "i": "EMRlhEQK44_V5804rsRvQ99Gtf7uDpYQqZuvrw0LhV3S",
  "ri": "EKfi58Jiv-NVqr6GOrxgxzhrE5RsDaH4QNwv9rCyZCwZ",
  "s": "EMwdW1RO1TvOmTMrli_fej8GYn-3tSl27xMyDDf0jigK",
  "a": {
    "d": "",
    "u": "0AAt-NwGI1OZzj7e52Jq9JDD",
    "i": "EP4CmMn6ZTM3oTq-iI-2TQdlwdMXF6a2WFWaeQQRULsn",
    "knownAs": "Alice",
    "minutes": 10,
    "dt": "2023-03-13T16:15:07.686737+00:00",
    "biometricHashes": ["EDIai3Wkd-Z_4cezz9nYEcCK3KNH5saLvZoS_84JL6NU"],
    "confirmedHandles": ["twitter:aliceIsntInWonderland", "mailto:alice@example.com", "github:alice-the-cryptoqueen"],
    "basis": "acquaintance",
    "caveats": "Loud conference; hard to hear Alice speaking."
  },
  "r": "EE1ycWdqBAE_4F-WsXZM83CrjpyCClYgPeINk104bLKX"
}
